### ISSUE TITLE
Destruction of other Mechs when pilot dies in BT Extended

### ISSUE THREAD

**Issue by lordruthermore** [ajkroeg/TisButAScratch#3] opened 2021-08-21 15:01 UTC
With BT Extended it often happens that when an enemy pilot dies, that can cause other OpFor mechs to also get destroyed.
Is this something that occurs with other modpacks like BTA and RT?

**Comment by ajkroeg** [comment] 2021-08-22 13:37
are you using the most recent release? its been a while since we saw this issue, but it would occur when units were getting the same GUID. in BTA/RT that unit was resolved a while ago using the most recent release.

is BEX officially using TBAS or are you just adding it on?

**Comment by victorlapin** [comment] 2021-09-28 13:06
Confirmed behavior when extra mod outside of RT/BTA. @ajkroeg this issue is about fetching and reusing the same pilot tag for several spawned AI pilots.

Example: I've encountered a lance of CMD-1B, CMD-2D and JVN-10A. This is the TBAS log for their spawn:

`INFO: 2021-09-28T17:17:36 - Added Recruit iGUID tag: iGUID_pilot_d2_recruit94e3508c-9969-4b13-bd42-1fd267832f14AI_TEMP_
INFO: 2021-09-28T17:17:36 - Fetched Recruit iGUID
INFO: 2021-09-28T17:17:36 - Recruit, iGUID_pilot_d2_recruit94e3508c-9969-4b13-bd42-1fd267832f14AI_TEMP_, piloting Commando, COM-1B missing, added to combatInjuriesMap
INFO: 2021-09-28T17:17:36 - Recruit missing, added to pilotInjuriesMap
INFO: 2021-09-28T17:17:36 - Initializing injury effects for Recruit
INFO: 2021-09-28T17:17:36 - Recruit calculated BloodBank and BloodCapacity: 2
INFO: 2021-09-28T17:17:36 - Fetched Recruit iGUID
INFO: 2021-09-28T17:17:36 - Initializing injury effects for Recruit
INFO: 2021-09-28T17:17:36 - Recruit calculated BloodBank and BloodCapacity: 2
INFO: 2021-09-28T17:17:36 - Fetched Recruit iGUID
INFO: 2021-09-28T17:17:36 - Initializing injury effects for Recruit
INFO: 2021-09-28T17:17:36 - Recruit calculated BloodBank and BloodCapacity: 2`

There was only one actual GUID reused 3 times.

**Comment by ajkroeg** [comment] 2021-09-28 14:14
Using most recent release? I'd need to see the full TBAS log, not just a snippet, as well as the full output_log.txt (and cleaned_output_log.txt if using FYLS).

@victorlapin are you also using BEX? I cannot replicate this using BTA/RT, nor using a bare-bones install (vanilla + TBAS only).

**Comment by victorlapin** [comment] 2021-09-28 14:28
I'm using standalone mods without any big modpack. I'll have a look at BEX (what mods are used there), and I'll get you FYLS and TBAS logs shortly.

**Comment by victorlapin** [comment] 2021-09-28 15:19
[TBAS.log](https://github.com/ajkroeg/TisButAScratch/files/7245407/TBAS.log)
[cleaned_output_log.txt](https://github.com/ajkroeg/TisButAScratch/files/7245410/cleaned_output_log.txt)
[output_log.txt](https://github.com/ajkroeg/TisButAScratch/files/7245413/output_log.txt)
[mods.txt](https://github.com/ajkroeg/TisButAScratch/files/7245452/mods.txt)

There you go. Things to notice:
1. I've played a recovery mission with 2 target spots (i.e. 2 enemy lances) with additional friendly lance spawned by MissionControl
2. All friendly pilots have gotten the same tag iGUID_pilot_d3_tacticiancd42b63f-6d3a-4a5c-bb7e-c628061aef04AI_TEMP_ (you can see all 4 of them having their turn in the log)
3. At least 3 enemy pilots have gotten tag iGUID_pilot_d3_pilot1c3ed08d-d5fc-4a21-892c-4dfefd175990AI_TEMP_, so debilitating and incapacitating one of them rendered the other 2 destroyed

Please ping me if I can provide anything else. All my installed mods are listed in mods.txt. Those marked as BTVL* contain only jsons and csv for additional or changed vanilla gear (me having fun, you know =))

**Comment by ajkroeg** [comment] 2021-09-29 00:33
very strange. @victorlapin can i also get the modtek.log and harmony_summary.log files? both should be in the `.modtek` folder.

**Comment by victorlapin** [comment] 2021-09-29 04:57
Sure thing, here they are:

[harmony_summary.log](https://github.com/ajkroeg/TisButAScratch/files/7248933/harmony_summary.log)
[ModTek.log](https://github.com/ajkroeg/TisButAScratch/files/7248937/ModTek.log)

**Comment by ajkroeg** [comment] 2021-09-29 15:19
@victorlapin @lordruthermore give the new release a try (v1.0.3.91) (just need to replace the dll, don't need to change anything else). ive run a couple tests and it seems to have taken care of it, but ill wait to close this until i hear from y'all.

**Comment by victorlapin** [comment] 2021-09-30 07:29
I'd say, looks good now. Every pilot gets its own tag.

**Comment by ajkroeg** [comment] 2021-09-30 11:11
appears to be fixed in v1.0.3.91

**Closed** 2021-09-30 11:11 UTC
